#!/bin/bash
df -H | grep -E '/$|/boot$' | awk '{ print $6 " " $5 }' | while read line;
  do
  disk=$(echo $line | awk '{ print $1 }')
  per=$(echo $line | awk '{ print $2 }' | tr -d %)
  if [ $per -ge 10 ]; then
  	echo "$disk is above the threshold. Currently at $per% usage" |
  	mail -s '$disk at $per % usage' root@localhost.localdomain
  	echo "$disk is above the threshold. Currently at $per% usage"
  fi
done